-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 27, 2023 at 09:52 AM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 8.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `bookworms`
--

-- --------------------------------------------------------

--
-- Table structure for table `books`
--

CREATE TABLE `books` (
  `ID` int(11) NOT NULL,
  `title` varchar(100) NOT NULL,
  `author` varchar(100) NOT NULL,
  `ISBN` varchar(20) NOT NULL,
  `description` varchar(4000) NOT NULL,
  `book_image` varchar(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `books`
--

INSERT INTO `books` (`ID`, `title`, `author`, `ISBN`, `description`, `book_image`) VALUES
(0, 'Momo', 'Michael Ende', '9783522621113', 'Momo, also known as The Grey Gentlemen or The Men in Grey, is a fantasy novel by Michael Ende, published in 1973. It is about the concept of time and how it is used by humans in modern societies. The full title in German (Momo oder Die seltsame Geschichte von den Zeit-Dieben und von dem Kind, das den Menschen die gestohlene Zeit zurückbrachte) translates to Momo, or the strange story of the time-thieves and the child who brought the stolen time back to the people. The book won the Deutscher Jugendliteraturpreis in 1974.', 'https://kbimages1-a.akamaihd.net/70b6db4b-7b4b-4703-b947-9fbe108d459e/1200/1200/False/momo-15.jpg'),
(1, 'The Wheel of Life', 'Elisabeth Kübler-Ross, M.D.', '9780684846316', 'A Memoir of Living and Dying: The memoirs of one of the world\'s foremost experts on death, dying and life after death. The book traces the path she followed from her birthplace in Switzerland to her present residence in Arizona. It explains how her work with relief organizations after World War II influenced her research on death and dying. Kubler-Ross shot to fame in 1969 upon the publication of her seminal work, \"On Death and Dying\". This book spells out her somewhat unconventional position on life after death as well as her more recent criticisms of the quality of care found in hospitals. Her own story, which takes into account her experiences as a wife and mother, is punctuated with behind-the-scenes accounts of her moving case studies.', 'https://m.media-amazon.com/images/I/41W36X4GW1L.jpg'),
(2, 'Untamed', 'Glennon Doyle', '9781984801258', '#1 NEW YORK TIMES BESTSELLER - OVER TWO MILLION COPIES SOLD! \"Packed with incredible insight about what it means to be a woman today.\"--Reese Witherspoon (Reese\'s Book Club Pick)\r\n\r\nIn her most revealing and powerful memoir yet, the activist, speaker, bestselling author, and \"patron saint of female empowerment\" (People) explores the joy and peace we discover when we stop striving to meet others\' expectations and start trusting the voice deep within us.\r\n\r\nNAMED ONE OF THE BEST BOOKS OF THE YEAR BY O: The Oprah Magazine - The Washington Post - Cosmopolitan - Marie Claire - Bloomberg - Parade - \"Untamed will liberate women--emotionally, spiritually, and physically. It is phenomenal.\"--Elizabeth Gilbert, author of City of Girls and Eat Pray Love\r\n\r\nThis is how you find yourself.\r\n\r\nThere is a voice of longing inside each woman. We strive so mightily to be good: good partners, daughters, mothers, employees, and friends. We hope all this striving will make us feel alive. Instead, it leaves us feeling weary, stuck, overwhelmed, and underwhelmed. We look at our lives and wonder: Wasn\'t it all supposed to be more beautiful than this? We quickly silence that question, telling ourselves to be grateful, hiding our discontent--even from ourselves.\r\n\r\nFor many years, Glennon Doyle denied her own discontent. Then, while speaking at a conference, she looked at a woman across the room and fell instantly in love. Three words flooded her mind: There She Is. At first, Glennon assumed these words came to her from on high. But she soon realized they had come to her from within. This was her own voice--the one she had buried beneath decades of numbing addictions, cultural conditioning, and institutional allegiances. This was the voice of the girl she had been before the world told her who to be. Glennon decided to quit abandoning herself and to instead abandon the world\'s expectations of her. She quit being good so she could be free. She quit pleasing and started living.\r\n\r\nSoulful and uproarious, forceful and tender, Untamed is both an intimate memoir and a galvanizing wake-up call. It is the story of how one woman learned that a responsible mother is not one who slowly dies for her children, but one who shows them how to fully live. It is the story of navigating divorce, forming a new blended family, and discovering that the brokenness or wholeness of a family depends not on its structure but on each member\'s ability to bring her full self to the table. And it is the story of how each of us can begin to trust ourselves enough to set boundaries, make peace with our bodies, honor our anger and heartbreak, and unleash our truest, wildest instincts so that we become women who can finally look at ourselves and say: There She Is.\r\n\r\nUntamed shows us how to be brave. As Glennon insists: The braver we are, the luckier we get.', 'https://m.media-amazon.com/images/I/91pIT84uoVL.jpg'),
(3, 'The Essential Rumi', 'Jalal al-Din Rumi (Author), Coleman Barks (Translator), John Moyne (Translator)', '978-0062509598', 'This revised and expanded edition of The Essential Rumi includes a new introduction by Coleman Barks and more than 80 never-before-published poems of Rumi.\r\n\r\nThrough his lyrical translations, Coleman Barks has been instrumental in bringing this exquisite literature to a remarkably wide range of readers, making the ecstatic, spiritual poetry of thirteenth-century Sufi Mystic Rumi more popular than ever. The Essential Rumi continues to be the bestselling of all Rumi books, and the definitive selection of his beautiful, mystical poetry.', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/0625/9780062509598.jpg'),
(4, 'The Forty Rules of Love', 'Elif Shafak', '978-0241972939', '*The international bestseller* \"Every true love and friendship is a story of unexpected transformation. If we are the same person before and after we loved, that means we haven\'t loved enough...\" Ella Rubinstein has a husband, three teenage children, and a pleasant home. Everything that should make her confident and fulfilled. Yet there is an emptiness at the heart of Ella\'s life - an emptiness once filled by love. So when Ella reads a manuscript about the thirteenth-century Sufi poet Rumi and Shams of Tabriz, and his forty rules of life and love, her world is turned upside down. She embarks on a journey to meet the mysterious author of this work. It is a quest infused with Sufi mysticism and verse, taking Ella and us into an exotic world where faith and love are heartbreakingly explored. . . \'Enlightening, enthralling. An affecting paean to faith and love\' Metro \'Colourfully woven and beguilingly intelligent\' Daily Telegraph \'The past and present fit together beautifully in a passionate defence of passion itself\' The Times', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/2419/9780241972939.jpg'),
(5, 'The Alchemist', 'Paulo Coelho (Author), Alan R. Clarke (Translator)', '978-0061122415', 'The Alchemist by Paulo Coelho continues to change the lives of its readers forever. With more than two million copies sold around the world, The Alchemist has established itself as a modern classic, universally admired.\r\n\r\nPaulo Coelho\'s masterpiece tells the magical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure as extravagant as any ever found.\r\n\r\nThe story of the treasures Santiago finds along the way teaches us, as only a few stories can, about the essential wisdom of listening to our hearts, learning to read the omens strewn along life\'s path, and, above all, following our dreams.', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/0612/9780061233845.jpg'),
(6, 'The Infinite Game', 'Simon Sinek', '9780241385630', 'NEW YORK TIMES BESTSELLER\r\n\r\nThe New York Times-bestselling author of Start With Why, Leaders Eat Last, and Together Is Better offers a bold new approach to business strategy by asking one question: are you playing the finite game or the infinite game?\r\n\r\nIn The Infinite Game, Sinek applies game theory to explore how great businesses achieve long-lasting success. He finds that building long-term value and healthy, enduring growth - that playing the infinite game - is the only thing that matters to your business.', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/2413/9780241385630.jpg'),
(7, 'The Four Agreements : A Practical Guide to Personal Freedom (A Toltec Wisdom Book)', 'Don Miguel Ruiz', '9781878424310', 'In The Four Agreements, bestselling author don Miguel Ruiz reveals the source of self-limiting beliefs that rob us of joy and create needless suffering. Based on ancient Toltec wisdom, The Four Agreements offer a powerful code of conduct that can rapidly transform our lives to a new experience of freedom, true happiness, and love.\r\n\r\n•  A New York Times bestseller for over a decade\r\n•  Translated into 46 languages worldwide\r\n \r\n“This book by don Miguel Ruiz, simple yet so powerful, has made a tremendous difference in how I think and act in every encounter.” — Oprah Winfrey\r\n\r\n“Don Miguel Ruiz’s book is a roadmap to enlightenment and freedom.” — Deepak Chopra, Author, The Seven Spiritual Laws of Success\r\n\r\n“An inspiring book with many great lessons.” — Wayne Dyer, Author, Real Magic\r\n\r\n“In the tradition of Castaneda, Ruiz distills essential Toltec wisdom, expressing with clarity and impeccability what it means for men and women to live as peaceful warriors in the modern world.” — Dan Millman, Author, Way of the Peaceful Warrior', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/8784/9781878424310.jpg'),
(8, 'The Tale of Tales', 'Giambattista Basile (Author), Nancy L. Canepa (Editor, Translator)', '9780143129141', 'Before the Brothers Grimm, before Charles Perrault, before Hans Christian Andersen, there was Giambattista Basile, a seventeenth-century poet from Naples, Italy, whom the Grimms credit with recording the first national collection of fairy tales. The Tale of Tales—also known as The Pentamerone—opens with Princess Zoza, unable to laugh no matter how funny the joke. Her father, the king, attempts to make her smile; instead he leaves her cursed, whereupon the prince she is destined to marry is snatched up by another woman. To expose this impostor and win back her rightful husband, Zoza contrives a storytelling extravaganza: fifty fairy tales to be told by ten sharp-tongued women (including Zoza in disguise) over five days.\r\n \r\nFunny and scary, romantic and gruesome—and featuring a childless queen who devours the heart of a sea monster cooked by a virgin, and who then gives birth the very next day; a lecherous king aroused by the voice of a woman, whom he courts unaware of her physical grotesqueness; and a king who raises a flea to monstrous size on his own blood, sparking a contest in which an ogre vies with men for the hand of the king’s daughter—The Tale of Tales is a fairy-tale treasure that prefigures Game of Thrones and other touchstones of worldwide fantasy literature.', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/1431/9780143129141.jpg'),
(9, 'Appetite', 'Nigel Slater', '9780609610787', '“If you decide to go through life without cooking you are missing something very, very special. You are losing out on one of the greatest pleasures you can have with your clothes on.” — Nigel Slater\r\n\r\nA chance comment spurred the heralded Observer columnist and wildly popular cookbook author Nigel Slater to write Appetite. A reader asked “If you don’t give me exact amounts in a recipe, then how will I know if it is right?” Slater realized the reader had so little confidence in his own cooking that he didn’t know what he liked unless he was told. Appetite is not about getting it right or wrong; it is about liking what you cook.\r\n\r\nTo help the everyday cook achieve culinary independence, Slater supplies the basics of relaxed, unpretentious, hearty cooking, written with his trademark humour and candour. Slater doesn’t believe in replicating restaurant-style theatricality to impress guests -- he simply loves food, and his love is evident on every page.\r\n\r\nSlater covers the philosophies of cooking, the basics to have on hand, and detailed descriptions of necessary equipment and ingredients. He tells you which wok to buy (the cheap one), and why it can pay to flirt with the fishmonger. There are sections on seasoning, a good long list of foods that pair well, and a large collection of recipes for soup, pasta, rice, vegetables, fish, meat, pastry and desserts. These are straightforward, easy-to-make dishes adapted for the North American cook -- every one a springboard to something new, different and delicious. And with full-colour photography throughout the book, Appetite is a feast for the eyes as well as the palate.', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/6096/9780609610787.jpg'),
(10, 'The Man Who Mistook His Wife for a Hat', 'Oliver Sacks', '9780330294911', 'In his most extraordinary book, the bestselling author of Awakenings and \"poet laureate of medicine” (The New York Times) recounts the case histories of patients inhabiting the compelling world of neurological disorders, from those who are no longer able to recognize common objects to those who gain extraordinary new skills.\r\nOliver Sacks’s The Man Who Mistook His Wife for a Hat tells the stories of individuals afflicted with perceptual and intellectual disorders: patients who have lost their memories and with them the greater part of their pasts; who are no longer able to recognize people and common objects; whose limbs seem alien to them; who lack some skills yet are gifted with uncanny artistic or mathematical talents. In Dr. Sacks’s splendid and sympathetic telling, his patients are deeply human and his tales are studies of struggles against incredible adversity. A great healer, Sacks never loses sight of medicine’s ultimate responsibility: “the suffering, afflicted, fighting human subject.”', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/3302/9780330294911.jpg'),
(11, 'Moranifesto', 'Caitlin Moran', '9780091949068', '\'I\'ve lived through ten iOS upgrades on my Mac - and that\'s just something I use to muck about on Twitter. Surely capitalism is due an upgrade or two?\'\r\n\r\nWhen Caitlin Moran sat down to choose her favourite pieces for her new book she realised that they all seemed to join up. Turns out, it\'s the same old problems and the same old ass-hats.\r\n\r\nThen she thought of the word \'Moranifesto\', and she knew what she had to do...\r\n\r\nThis is Caitlin\'s engaging and amusing rallying call for our times. Combining the best of her recent columns with lots of new writing unique to this book, Caitlin deals with topics as pressing and diverse as 1980s swearing, benefits, boarding schools, and why the internet is like a drunken toddler.\r\n\r\nAnd whilst never afraid to address the big issues of the day - such as Benedict Cumberbatch and duffel coats - Caitlin also makes a passionate effort to understand our 21st century society and presents us with her \'Moranifesto\' for making the world a better place.\r\n\r\nThe polite revolution starts here! Please.', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/0919/9780091949068.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `books`
--
ALTER TABLE `books`
  ADD PRIMARY KEY (`ID`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
